name: Nightly Release

on:
  workflow_call:

jobs:
    createBranch:
        uses: ./.github/workflows/create_js_branch.yaml
        with:
           version: nightly-$(date +'%Y%m%d')
    createRelease:
        needs: [createBranch]
        permissions:
            contents: write
        uses: ./.github/workflows/create_release.yaml
        with:
            branch: releases/nightly-$(date +'%Y%m%d')
            version: nightly-$(date +'%Y%m%d')
            