name: Nightly Release

on:
  workflow_call:

jobs:
    releaseDate:   
        runs-on: ubuntu-latest
        steps:
            - name: output current date
              run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    createBranch: 
        needs: [releaseDate]    
        uses: ./.github/workflows/create_js_branch.yaml
        with: 
            version: nightly-${{needs.releaseDate.outputs.date}}
    createRelease:
        needs: [releaseDate, createBranch]
        permissions:
            contents: write
        uses: ./.github/workflows/create_release.yaml
        with:
            branch: releases/nightly-nightly-${{needs.releaseDate.outputs.date}}
            version: nightly-nightly-${{needs.releaseDate.outputs.date}}
            