name: Nightly Release

on:
  workflow_call:

jobs:
    currentDate:   
        runs-on: ubuntu-latest
        steps:
            - name: Get current date
              run: echo "DATE=$('%Y-%m-%d')" >> $GITHUB_ENV
    createBranch:     
        uses: ./.github/workflows/create_js_branch.yaml
        with: 
            version: nightly-${DATE}
    createRelease:
        needs: [createBranch]
        permissions:
            contents: write
        uses: ./.github/workflows/create_release.yaml
        with:
            branch: releases/nightly-${DATE}
            version: nightly-${DATE}
            