name: nightly release

on:
  workflow_call:

jobs:
    releaseDate:   
        runs-on: ubuntu-latest
        outputs:
            date: ${{steps.releaseDate.outputs.date}}
        steps:
        - name: output current date
          id: releaseDate
          run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    createBranch:     
        uses: ./.github/workflows/create_js_branch.yaml
        with:
           version: nightly
    createRelease:
        needs: [createBranch]
        permissions:
            contents: write
        uses: ./.github/workflows/create_release.yaml
        with:
            branch: releases/nightly
            version: nightly-$(date +'%Y%m%d')
            