name: Nightly Release

on:
  workflow_call:

jobs:
    switchBranch: 
        uses: ./.github/workflows/switch_js_branch.yaml
        with: 
            version: nightly
    createRelease:
        needs: [switchBranch]
        permissions:
            contents: write
        uses: ./.github/workflows/create_release.yaml
        with:
            branch: releases/nightly
            version: nightly
            