name: release

on:
  push:
    branches:
      - main
    paths:
      - CHANGELOG.md
  workflow_dispatch:

jobs:
  changelog:
    uses: ./.github/workflows/extract_changelog.yaml
    with:
      changelogPath: ./CHANGELOG.md
  checkVersion:
    needs: changelog
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.tag-exists.outputs.exists }}
    steps:
      - name: check if tag exists
        uses: mukunku/tag-exists-action@5dfe2bf779fe5259360bb10b2041676713dcc8a3 # v1.1.0
        id: tag-exists
        with:
          tag: ${{ needs.changelog.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  createBranch:
    needs: [changelog, checkVersion]
    if: needs.checkVersion.outputs.exists == 'false'
    uses: ./.github/workflows/create_js_branch.yaml
    with:
        version: ${{ needs.changelog.outputs.version }}
  createRelease:
      needs: [changelog, checkVersion, createBranch]
      permissions:
        contents: write
      if: needs.checkVersion.outputs.exists == 'false'
      uses: ./.github/workflows/create_release.yaml
      with:
        branch: ${{ github.ref }}
        version: ${{ needs.changelog.outputs.version }}
        body: ${{ needs.changelog.outputs.body }}
